### PR TITLE
Breaks Dark Transparency

### PR DESCRIPTION
**Pull request by squee666**

### CODE REVIEW

**Comment by ZXNova** [comment]
Basically commenting to say I have the same issue, and it has been like this for over a month. Dark transparency is messed up, and the discord.me/mrrobotserver link that's advertised with the theme is expired. As well as the so called "options" for discord reborn don't even show up. This is reborn version 7.3 right?

**Comment by ryudragon98** [comment]
the options are custom css stuff that you can find in the server for the themes.

**Comment by squee666** [comment]
Also transparency worms fine it's just that omni overwrote some new transparency in profiles I added a week or so ago. Rest worms fine

**Comment by ZXNova** [comment]
So there's custom css in this server for themes? Where is it?

**Comment by ryudragon98** [comment]
https://discord.gg/MpWmqQk

**Comment by ZXNova** [comment]
That invite link is expired

**Pull request closed without merging**
